# Generated by Django 5.2.5 on 2025-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
